version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - pwd
      - ls -la
      - echo "Installing dependencies..."
      - npm install
  
  build:
    commands:
      - echo "Building..."
      - npm run build

artifacts:
  base-directory: dist
  files:
    - '**/*'